// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oenczvadivmgmbqzjpid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbmN6dmFkaXZtZ21icXpqcGlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjU0MjQsImV4cCI6MjA2MDU0MTQyNH0.IoRGoKihOmlJsXvucBMyI_sJ5eLo2jRXm3nLaqxaMxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);